spring.datasource.url=jdbc:mysql://localhost:3306/DB-Designer
spring.datasource.username=root
spring.datasource.password=root-password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.naming-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto = update